Updated the github workflow to generate the JSON schemas and Definitions for Kuma components
meshery/meshery-kuma pull request #184
Opened 2021-08-08 14:33 UTC by Shreyas220

Signed-off-by: Shreyas220 <shreyas.ny@gmail.com>

**Description**
Updated the github workflow to generate the JSON schemas and Definitions for Kuma components
 #174  
**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2021-08-08 18:54 UTC, sayantan1413 requested changes
Great work @Shreyas220🎉 . Some minor changes requested 😃

2021-08-08 18:54 UTC, sayantan1413 commented on .github/workflows/update-oam-defs.yml
> +          cat .github/.env > $GITHUB_ENV
Hey @Shreyas220 consider changing this to https://github.com/meshery/meshery-osm/blob/master/.github/workflows/update-oam-defs.yml#L24-L31

2021-08-08 18:54 UTC, sayantan1413 commented on .github/workflows/update-oam-defs.yml
> +          echo "CURRENT_KUMA_VERSION=$NEW_KUMA_VERSION" > .github/.env
We can delete this as we don't need to take the version from .env that was present in .github.

2021-08-08 18:54 UTC, sayantan1413 commented on .github/workflows/update-oam-defs.yml
> +          rm -rf util kuma-*
Consider changing it to `rm -rf util`

2021-08-08 18:58 UTC, sayantan1413 requested changes

2021-08-08 18:58 UTC, sayantan1413 commented on .github/workflows/update-oam-defs.yml
> +          cd util
Consider changing this in this way https://github.com/meshery/meshery-osm/blob/master/.github/workflows/update-oam-defs.yml#L66-L70

2021-08-09 08:51 UTC, sayantan1413 requested changes

2021-08-09 08:51 UTC, sayantan1413 commented on .github/workflows/update-oam-defs.yml
> +          meshName=osm
meshName=kuma

2021-08-09 08:51 UTC, sayantan1413 commented on .github/workflows/update-oam-defs.yml
> +          dirPath=../templates/oam/workloads/workloads-$NEW_OSM_VERSION
$NEW_KUMA_VERSION

2021-08-09 10:45 UTC, Shreyas220 commented
@sayantan1413 @DelusionalOptimist The components aren't being generated, it is getting skipped

2021-08-09 11:00 UTC, sayantan1413 commented
Hey @Shreyas220 can you please replicate this changes https://github.com/sayantan1413/meshery-kuma/blob/master/.github/workflows/update-oam-defs.yml to your current change. I think this will solve the problem of the workflow getting skipped.

2021-08-09 14:01 UTC, Shreyas220 commented
https://github.com/Shreyas220/meshery-kuma/tree/master/templates/oam/workloads/workloads-1.2.2

2021-08-09 15:09 UTC, sayantan1413 requested changes

2021-08-09 17:54 UTC, leecalcote commented
@Shreyas220 will you resolve any comments that you have addressed?

2021-08-09 19:47 UTC, DelusionalOptimist commented
@sayantan1413 looking good? anything to add?

2021-08-09 20:04 UTC, DelusionalOptimist approved these changes
LGTM :rocket:.
Thanks @Shreyas220 and @sayantan1413 :raised_hands:

2021-08-09 20:05 UTC, merged