Fixed Logo of Layer5 with Meshery
meshery/meshery-kuma pull request #383
Opened 2023-04-21 18:23 UTC by yash37158

**Description**

This PR fixes #
This PR fixes the existing layer5 celebration logo with the meshery celebration as meshery-kuma is under the organization meshery
**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-04-24 10:44 UTC, yash37158 commented
Hey @leecalcote any comments on this ?

2023-04-24 19:27 UTC, leecalcote commented
@yash37158  please engage another maintainer. I will only slow you down.

In the meantime, you can amend your commit(s) with a signoff to pass DCO.

2023-04-25 10:04 UTC, yash37158 commented
Sure @leecalcote

2023-04-25 12:12 UTC, Chadha93 commented on .github/config.yml
> +  Thanks for your contribution to the Layer5 and Meshery community! :tada:
```suggestion
  Thanks for your contribution to Meshery! :tada:
```

2023-04-25 13:55 UTC, thisiskaransgit requested changes

2023-04-25 13:55 UTC, thisiskaransgit commented on .github/config.yml
> +  ![Congrats!](https://raw.githubusercontent.com/meshery/meshery.io/master/.github/welcome/meshery-celebration-light.svg)
Update the links with `meshery-kuma`'s path
https://github.com/meshery/meshery-kuma/blob/master/.github/welcome/meshery-celebration-dark.svg
https://github.com/meshery/meshery-kuma/blob/master/.github/welcome/meshery-celebration-light.svg

2023-04-25 13:57 UTC, thisiskaransgit commented
Mention the fixed issue in description.

2023-05-17 08:49 UTC, closed without merging