docs: issue #394 Issue Template Updates for Figma link w/signoff
meshery/meshery-kuma pull request #396
Opened 2023-07-12 10:11 UTC by aryanas159

**Description**

This PR fixes #
issue #394 
**Notes for Reviewers**
Added necessary information as provided in the issue.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [✅ ] Yes, I signed my commits.

2023-07-12 11:10 UTC, leecalcote requested changes
Thanks!

2023-07-12 11:10 UTC, leecalcote commented on .github/ISSUE_TEMPLATE/bug_report.md
> +1. All references to Figma include the "open invite" link.
This section was accidentally included in the issue description. please remove

2023-07-12 20:57 UTC, leecalcote commented
@aryanas159 this is missing the desired changes. @yashchaddha will you give @aryanas159 some pointers (show him your PR as an example) and let's get him reassigned to another open one of these issues.

2023-07-12 20:57 UTC, closed without merging

2023-07-12 23:22 UTC, yashchaddha commented
Sure @leecalcote i will.

Hi @aryanas159 lets sync up to resolve another similar issue with an effective PR

2023-07-13 06:06 UTC, aryanas159 commented
@yashchaddha  sure, what should we work on?

2023-07-13 06:32 UTC, yashchaddha commented
Hi @aryanas159 lets work on

https://github.com/meshery/meshsync/issues/210

comment there so that @leecalcote  can assign you!

Thanks